### PR TITLE
Add map operator for Observable

### PR DESCRIPTION
**Pull request by wwilsman**
## Purpose
The action$ in our epic inherits the Observable created in stripes-core. Any operators chained from this action$ must be defined in stripes-core. However when we create our own Observable using `from` or `of` we need to add the operators we expect to use in our own app

## Approach
- Removes `switchMap` as that is now defined in `stripes-core`
- Adds `map` since we need it when we use `Observable.from(request)`

### CODE REVIEW

**Comment by wwilsman** [comment]
This needs our fork of `stripes-core` to be rebased with upstream

**Comment by elrickvm** [comment]
I opened the PR on stripes-core to import switchMap. For some reason i couldn't requests review in that repo but once that is merge then we are good for this.

**Comment by wwilsman** [comment]
@elrickvm actually Hongwei already made a commit to `stripes-core` you can close that PR now

**Comment by elrickvm** [comment]
Yep @wwilsman good to go its closed.

**Pull request merged**
