### PR TITLE
Show Search Results Total

### PR DESCRIPTION
**Pull request by wwilsman**
## Purpose
Show the search results total for vendors, packages, and titles

## Approach
Copies how the total number is displayed for ui-users (under the results pane header).

## Screenshots
image

### CODE REVIEW

**Comment by wwilsman** [comment]
This relies on #119 so we can easily pull the results total from the JSON API payload meta

**Comment by wwilsman** [comment]
Ready for final review 👍

**Comment by cherewaty** [comment]
I added a commit with a newer way to set pane header titles.

**Comment by cherewaty** [comment]
Additional commits removed - I'll do that in another PR, since it involves some test changes.

**Pull request merged**
